### PR TITLE
proposed solution for ex 1.3,1.5

### PR DESCRIPTION
**Pull request by vincenzonetti**
Here are the solution of the exercises mentioned above. 
I don't remember if the files should be named in a specif way.

### CODE REVIEW

**Comment by giuspek** [comment]
The names are fine this way! Now I'll check them.

**Comment by giuspek** [comment]
Ex1.3 is fine and it would considered 100% correct, but there are some minor points you should address. First, when dealing with SAT problems, make sure the reader of your file has a clear meaning of what FALSE and TRUE represent (in this case FALSE is guilty, but with bigger problems inferring it could be difficult). Add a comment to fix it.
Moreover, the condition stated by C could be drastically simplified: (not A) or (not B) already embed the 3 conditions (A only guilty, B only guilty, both guilty), so you can shorten it.

**Comment by giuspek** [comment]
Ex1.5 is also correct for both the 2-coloring problem and the 3-coloring version. Similarly to ex1.3, add some comments explaining what each variable means, and also add comments to report the results of your solver (better grades for your exam if I have a better understanding of your code :) ). Highly appreciate the comments before every hidden condition 💯 

PS: small trick: you can compact lines 29-39 (setting only one color at a time for each node) into 4 lines by using XORs (XOR = one true and one false) ;)

**Comment by giuspek** [comment]
Solution for ex1.4 is almost perfect 💯 
When checking if the solution is unique, please make sure that you negate the ENTIRE assignment, not only one variable inside it (there could be a solution where one single variable has still the same truth value but all the others change).

**Comment by giuspek** [comment]
And that's it! Fix these minor points, then I'll merge them 👍

**Comment by giuspek** [comment]
I noticed you started pushing the exercises for Lab 2. Is the Queen exercise still in the making? Or did you upload the wrong file? 
BTW, the other solutions are fine!

**Comment by vincenzonetti** [comment]
> I noticed you started pushing the exercises for Lab 2. Is the Queen exercise still in the making? Or did you upload the wrong file? BTW, the other solutions are fine!

Yes queen exercises is still in the making

**Comment by giuspek** [comment]
Perfect! I'll merge the current solutions for te time being.

**Pull request merged**
